wandb_version: 1

task:
  desc: null
  value: detect
mode:
  desc: null
  value: train
model:
  desc: null
  value: yolov8n.pt
data:
  desc: null
  value: C:/Users/LMMISTA-WAP265/YOLOV8_mlops/mlops/data/Mydataset/customdata.yaml
epochs:
  desc: null
  value: 5
patience:
  desc: null
  value: 50
batch:
  desc: null
  value: 16
imgsz:
  desc: null
  value: 640
save:
  desc: null
  value: true
save_period:
  desc: null
  value: -1
cache:
  desc: null
  value: false
device:
  desc: null
  value: null
workers:
  desc: null
  value: 8
project:
  desc: null
  value: ultralytics
name:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
pretrained:
  desc: null
  value: true
optimizer:
  desc: null
  value: auto
verbose:
  desc: null
  value: true
seed:
  desc: null
  value: 0
deterministic:
  desc: null
  value: true
single_cls:
  desc: null
  value: false
rect:
  desc: null
  value: false
cos_lr:
  desc: null
  value: false
close_mosaic:
  desc: null
  value: 10
resume:
  desc: null
  value: false
amp:
  desc: null
  value: true
fraction:
  desc: null
  value: 1.0
profile:
  desc: null
  value: false
freeze:
  desc: null
  value: null
overlap_mask:
  desc: null
  value: true
mask_ratio:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.0
val:
  desc: null
  value: true
split:
  desc: null
  value: val
save_json:
  desc: null
  value: false
save_hybrid:
  desc: null
  value: false
conf:
  desc: null
  value: null
iou:
  desc: null
  value: 0.7
max_det:
  desc: null
  value: 300
half:
  desc: null
  value: false
dnn:
  desc: null
  value: false
plots:
  desc: null
  value: true
source:
  desc: null
  value: null
show:
  desc: null
  value: false
save_txt:
  desc: null
  value: false
save_conf:
  desc: null
  value: false
save_crop:
  desc: null
  value: false
show_labels:
  desc: null
  value: true
show_conf:
  desc: null
  value: true
vid_stride:
  desc: null
  value: 1
stream_buffer:
  desc: null
  value: false
line_width:
  desc: null
  value: null
visualize:
  desc: null
  value: false
augment:
  desc: null
  value: false
agnostic_nms:
  desc: null
  value: false
classes:
  desc: null
  value: null
retina_masks:
  desc: null
  value: false
boxes:
  desc: null
  value: true
format:
  desc: null
  value: torchscript
keras:
  desc: null
  value: false
optimize:
  desc: null
  value: false
int8:
  desc: null
  value: false
dynamic:
  desc: null
  value: false
simplify:
  desc: null
  value: false
opset:
  desc: null
  value: null
workspace:
  desc: null
  value: 4
nms:
  desc: null
  value: false
lr0:
  desc: null
  value: 0.01
lrf:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.937
weight_decay:
  desc: null
  value: 0.0005
warmup_epochs:
  desc: null
  value: 3.0
warmup_momentum:
  desc: null
  value: 0.8
warmup_bias_lr:
  desc: null
  value: 0.1
box:
  desc: null
  value: 7.5
cls:
  desc: null
  value: 0.5
dfl:
  desc: null
  value: 1.5
pose:
  desc: null
  value: 12.0
kobj:
  desc: null
  value: 1.0
label_smoothing:
  desc: null
  value: 0.0
nbs:
  desc: null
  value: 64
hsv_h:
  desc: null
  value: 0.015
hsv_s:
  desc: null
  value: 0.7
hsv_v:
  desc: null
  value: 0.4
degrees:
  desc: null
  value: 0.0
translate:
  desc: null
  value: 0.1
scale:
  desc: null
  value: 0.5
shear:
  desc: null
  value: 0.0
perspective:
  desc: null
  value: 0.0
flipud:
  desc: null
  value: 0.0
fliplr:
  desc: null
  value: 0.5
mosaic:
  desc: null
  value: 1.0
mixup:
  desc: null
  value: 0.0
copy_paste:
  desc: null
  value: 0.0
cfg:
  desc: null
  value: null
tracker:
  desc: null
  value: botsort.yaml
save_dir:
  desc: null
  value: ultralytics\train4
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696849719.411648
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 16
      - 19
      - 23
      - 47
      4: 3.11.5
      5: 0.15.12
      6: 4.34.0
      8:
      - 3
      - 5
      13: windows-amd64
train:
  desc: null
  value:
    task: detect
    mode: train
    model: yolov8n.pt
    data: C:/Users/LMMISTA-WAP265/YOLOV8_mlops/mlops/data/Mydataset/customdata.yaml
    epochs: 5
    patience: 50
    batch: 16
    imgsz: 640
    save: true
    save_period: -1
    cache: false
    device: null
    workers: 8
    project: ultralytics
    name: null
    exist_ok: false
    pretrained: true
    optimizer: auto
    verbose: true
    seed: 0
    deterministic: true
    single_cls: false
    rect: false
    cos_lr: false
    close_mosaic: 10
    resume: false
    amp: true
    fraction: 1.0
    profile: false
    freeze: null
    overlap_mask: true
    mask_ratio: 4
    dropout: 0.0
    val: true
    split: val
    save_json: false
    save_hybrid: false
    conf: null
    iou: 0.7
    max_det: 300
    half: false
    dnn: false
    plots: true
    source: null
    show: false
    save_txt: false
    save_conf: false
    save_crop: false
    show_labels: true
    show_conf: true
    vid_stride: 1
    stream_buffer: false
    line_width: null
    visualize: false
    augment: false
    agnostic_nms: false
    classes: null
    retina_masks: false
    boxes: true
    format: torchscript
    keras: false
    optimize: false
    int8: false
    dynamic: false
    simplify: false
    opset: null
    workspace: 4
    nms: false
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.0
    box: 7.5
    cls: 0.5
    dfl: 1.5
    pose: 12.0
    kobj: 1.0
    label_smoothing: 0.0
    nbs: 64
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    cfg: null
    tracker: botsort.yaml
    save_dir: ultralytics\train4
prediction_configs:
  desc: null
  value:
    task: detect
    mode: predict
    model: yolov8n.pt
    data: C:/Users/LMMISTA-WAP265/YOLOV8_mlops/mlops/data/Mydataset/customdata.yaml
    epochs: 5
    patience: 50
    batch: 16
    imgsz: 640
    save: false
    save_period: -1
    cache: false
    device: null
    workers: 8
    project: ultralytics
    name: null
    exist_ok: false
    pretrained: true
    optimizer: auto
    verbose: true
    seed: 0
    deterministic: true
    single_cls: false
    rect: false
    cos_lr: false
    close_mosaic: 10
    resume: false
    amp: true
    fraction: 1.0
    profile: false
    freeze: null
    overlap_mask: true
    mask_ratio: 4
    dropout: 0.0
    val: true
    split: val
    save_json: false
    save_hybrid: false
    conf: 0.25
    iou: 0.7
    max_det: 300
    half: false
    dnn: false
    plots: true
    source: null
    show: false
    save_txt: false
    save_conf: false
    save_crop: false
    show_labels: true
    show_conf: true
    vid_stride: 1
    stream_buffer: false
    line_width: null
    visualize: false
    augment: false
    agnostic_nms: false
    classes: null
    retina_masks: false
    boxes: true
    format: torchscript
    keras: false
    optimize: false
    int8: false
    dynamic: false
    simplify: false
    opset: null
    workspace: 4
    nms: false
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.0
    box: 7.5
    cls: 0.5
    dfl: 1.5
    pose: 12.0
    kobj: 1.0
    label_smoothing: 0.0
    nbs: 64
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    cfg: null
    tracker: botsort.yaml
